project:
  name: cfn-abi-crowdstrike-fcs
  owner: support@crowdstrike.com # to be updated
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
  - us-east-1

tests:
  horizon-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      pOrganizationId: $[taskcat_ssm_/crowdstrike/organization-id]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  horizon-test-ct:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      pOrganizationId: $[taskcat_ssm_/crowdstrike/organization-id]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      CreateOrgTrail: "true"
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
