project:
  name: cfn-abi-crowdstrike-fcs
  owner: support@crowdstrike.com # to be updated
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
  - us-east-1

tests:
  cw-test:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-ct:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      CreateOrgTrail: "true"
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-ssm:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      EnableSSMDistributor: "true"
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-smlambda:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      APICredentialsStorageMode: "lambda"
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-all:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
      EnableSSMDistributor: "true"
      CreateOrgTrail: "true"
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml
  cw-test-nonct:
    parameters:
      FalconClientID: $[taskcat_ssm_/crowdstrike/falcon_client_id]
      FalconSecret: $[taskcat_ssm_/crowdstrike/falcon_secret]
      SourceS3BucketName: $[taskcat_autobucket]
      S3BucketRegion: $[taskcat_current_region]
      ProvisionOU: $[taskcat_ssm_/crowdstrike/provision-ou]
      CreateOrgTrail: "true"
      ExcludeRegions: $[taskcat_ssm_/crowdstrike/exclude_regions]
    regions:
    - us-east-1
    template: templates/crowdstrike_init_stack.yaml