---
AWSTemplateFormatVersion: 2010-09-09
Description: Create EventBridge Rules to enable CrowdStrike Falcon CSPM

Parameters:
  CSAccountNumber: 
    Description: Crowdstrike account number
    Type: String
    MinLength: 12
    MaxLength: 12
  CSEventBusName:
    Description: CrowdStrike Event Bridge Name
    Type: String

Resources:
  CrowdStrikeEventBusRule: 
    Type: AWS::Events::Rule
    Properties:
      Name: cs-cloudtrail-events-ioa-rule
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
          - AWS Console Sign In via CloudTrail
          - AWS Service Event via CloudTrail
        detail:
          eventName:
            anything-but:
              - InvokeExecution
          readOnly:
            - false
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${CSAccountNumber}:event-bus/${CSEventBusName}"
          RoleArn: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/CrowdStrikeCSPMEventBridge"
          Id: "CrowdStrikeCentralizeEvents"

  CrowdStrikeEventBusRuleRO:
    Type: AWS::Events::Rule
    Properties:
      Name: cs-cloudtrail-events-readonly-rule
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
          - AWS Console Sign In via CloudTrail
          - AWS Service Event via CloudTrail
        detail:
          readOnly:
            - true
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${CSAccountNumber}:event-bus/${CSEventBusName}"
          RoleArn: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/CrowdStrikeCSPMEventBridge"
          Id: "CrowdStrikeCentralizeEvents"
